//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFernandezVentaProducto
    {
        public int IdVentaProducto { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdProductoSucursal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual JFernandezProductos JFernandezProductos { get; set; }
        public virtual JFernandezProductoSucursal JFernandezProductoSucursal { get; set; }
        public virtual JFernandezVenta JFernandezVenta { get; set; }
    }
}
