//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFernandezProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JFernandezProductos()
        {
            this.JFernandezProductoSucursal = new HashSet<JFernandezProductoSucursal>();
            this.JFernandezVentaProducto = new HashSet<JFernandezVentaProducto>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public byte[] Image { get; set; }
    
        public virtual JFernandezDepartamento JFernandezDepartamento { get; set; }
        public virtual JFernandezProveedor JFernandezProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFernandezProductoSucursal> JFernandezProductoSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFernandezVentaProducto> JFernandezVentaProducto { get; set; }
    }
}
