//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_Consola.ServiceReferenceDepartamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Departamento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Area))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDepartamento.IDepartamento")]
    public interface IDepartamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/AddDepartamento", ReplyAction="http://tempuri.org/IDepartamento/AddDepartamentoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_Consola.ServiceReferenceDepartamento.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        PL_Consola.ServiceReferenceDepartamento.Result AddDepartamento(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/AddDepartamento", ReplyAction="http://tempuri.org/IDepartamento/AddDepartamentoResponse")]
        System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> AddDepartamentoAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/DeleteDepartamento", ReplyAction="http://tempuri.org/IDepartamento/DeleteDepartamentoResponse")]
        PL_Consola.ServiceReferenceDepartamento.Result DeleteDepartamento(int departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/DeleteDepartamento", ReplyAction="http://tempuri.org/IDepartamento/DeleteDepartamentoResponse")]
        System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> DeleteDepartamentoAsync(int departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/UpdateDepartamento", ReplyAction="http://tempuri.org/IDepartamento/UpdateDepartamentoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_Consola.ServiceReferenceDepartamento.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        PL_Consola.ServiceReferenceDepartamento.Result UpdateDepartamento(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/UpdateDepartamento", ReplyAction="http://tempuri.org/IDepartamento/UpdateDepartamentoResponse")]
        System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> UpdateDepartamentoAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/GetAllDepartamento", ReplyAction="http://tempuri.org/IDepartamento/GetAllDepartamentoResponse")]
        PL_Consola.ServiceReferenceDepartamento.Result GetAllDepartamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartamento/GetAllDepartamento", ReplyAction="http://tempuri.org/IDepartamento/GetAllDepartamentoResponse")]
        System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> GetAllDepartamentoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartamentoChannel : PL_Consola.ServiceReferenceDepartamento.IDepartamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartamentoClient : System.ServiceModel.ClientBase<PL_Consola.ServiceReferenceDepartamento.IDepartamento>, PL_Consola.ServiceReferenceDepartamento.IDepartamento {
        
        public DepartamentoClient() {
        }
        
        public DepartamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_Consola.ServiceReferenceDepartamento.Result AddDepartamento(ML.Departamento departamento) {
            return base.Channel.AddDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> AddDepartamentoAsync(ML.Departamento departamento) {
            return base.Channel.AddDepartamentoAsync(departamento);
        }
        
        public PL_Consola.ServiceReferenceDepartamento.Result DeleteDepartamento(int departamento) {
            return base.Channel.DeleteDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> DeleteDepartamentoAsync(int departamento) {
            return base.Channel.DeleteDepartamentoAsync(departamento);
        }
        
        public PL_Consola.ServiceReferenceDepartamento.Result UpdateDepartamento(ML.Departamento departamento) {
            return base.Channel.UpdateDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> UpdateDepartamentoAsync(ML.Departamento departamento) {
            return base.Channel.UpdateDepartamentoAsync(departamento);
        }
        
        public PL_Consola.ServiceReferenceDepartamento.Result GetAllDepartamento() {
            return base.Channel.GetAllDepartamento();
        }
        
        public System.Threading.Tasks.Task<PL_Consola.ServiceReferenceDepartamento.Result> GetAllDepartamentoAsync() {
            return base.Channel.GetAllDepartamentoAsync();
        }
    }
}
